name = "carohans"
compatibility_date = "2024-09-23"
main = "apps/web/.open-next/worker.js"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "apps/web/.open-next/assets"
binding = "ASSETS"
